[workspace]

members = [
    "agg-p6",
    "agg-p13",
    "agg-p20",
    "agg-p27",
    "agg-p33",
    "agg-p34",
]

[workspace.dependencies]
dioxus = "0.4.0"
dioxus-web = "0.4.0"
gloo-dialogs = "0.2.0"
