[package]
name = "agg-p48"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { workspace = true }
dioxus-web = { workspace = true }
async-std = { workspace = true }
chrono = "0.4.26"
